### ISSUE TITLE
Only using a single core

### ISSUE THREAD

**Issue by NickSlade** [bram0101/openVDB_mayaGUI#1]
Hi Bram,
Thanks for your work on this plugin, easy to install and use.

I'm currently exporting a single frame from my Maya fluids cache to vdb as a test and its very slow. I checked Task Manager and noticed that its only using a single core. Is there a way to have it use all available cores?

I'm using Maya 2018 on Windows 10.

Thanks

**Comment by bram0101** [comment]
Hi Nick,

The plugin is written to only use one core. It is technically possible to rewrite the plugin so that it uses more cores. Unfortunately, I do not have the time to rewrite it.

The plugin is fully open source with the MIT license, so I encourage anyone, who is wanting to, to add in the features that they miss.

Enabling the 'textured' checkbox does make the exporting a lot slower. If you do not need the fluid's textures baked into it, then I recommend to disable the 'textured' checkbox.

**Comment by NickSlade** [comment]
Hi Bram,

Thanks for your prompt reply. Unfortunately I don't have the technical knowledge to rewrite the plugin so will have to do with this for now and factor it into my project time.

Thanks again
