### ISSUE TITLE
Any working build for Maya 2018.3 Windows 10?

### ISSUE THREAD

**Issue by Githomie** [bram0101/openVDB_mayaGUI#2]
I'm on Maya 2018.3 / Windows 10 and the compiled version doesn't seem to run.

It either doesn't show up in the plugin window, or if I put all the files into a single directory and edit the mod file, it throws pluginWin.mel error line 290 that it can't find / load the specified module.

I'm not configured to recompile it myself, but I might see about setting up a testbox to fool around with that this weekend. Wondering if there's anything more obvious I'm missing.

Couldn't find much help online.

**Comment by bram0101** [comment]
If it doesn't show up in the plugin window or gives that specific error, then I do not believe that the issue is with compiling, but with how it is set up.

Just to be sure, below is a walk-through of setting up the plugin.
1. We are going to install it in `C:/Program Files/openVDB_mayaGUI`. You can choose a different location, but just for the sake of this walk-through it's in program files.
2. Download the repository. If you changed things in the files, I'd recommend to just re-download it.
3. Copy over the contents of `maya_plugin` into `C:/Program Files/openVDB_mayaGUI`. The result should look like this: 

```
C:
    Program Files
        openVDB_mayaGUI
            files
                bin
                    Half.dll
                    openVDB_mayaGUI.mll
                    openvdb.dll
                scripts
                    openvdb_mayagui.mel
            modFile.mod
```
4. Navigate to your Maya environment file. It probably is placed in `Documents/maya/2018/Maya.env`
5. Add the following line in the file: `MAYA_MODULE_PATH = C:/Program Files/openVDB_mayaGUI`. If there is already a line with MAYA_MODULE_PATH, then you can append the path with a `;`. It would then look like this: `MAYA_MODULE_PATH = C:/some/stuff;C:/Program Files/openVDB_mayaGUI`
6. Start Maya and load the plugin in the plugin window.

Would you be able to try this?

**Comment by Githomie** [comment]
Thanks, it now loads properly. I was misreading the instructions and putting it under "MAYA_PLUG_IN_PATH" since that's where all my other plugins went and I didn't notice it was something different. Once I added a separate "MAYA_MODULE_PATH" on a new line in Maya.env and set it appropriately, the plugin now loads.

For anyone else who makes the same mistake, you need to have two separate lines in your Maya.env file:
MAYA_PLUG_IN_PATH=[Standard path where you register most plugins]
MAYA_MODULE_PATH=C:\Program Files\openVDB_mayaGUI [or whatever directory you put openVDB_mayaGUI in]
...

Thank you so much for your work on this. Having openVDB functionality in Maya is such a wonderful thing!
